---
title: "workshop"
author: "Vivienne Foroughirad"
date: "December 3, 2018"
output: 
  html_document:
    keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cape Hatteras BRS Analysis

Load in the libraries and library paths

```{r echo=FALSE}
.libPaths("C:/Users/froug/OneDrive/Documents/R/win-library/3.5")

library(dplyr, lib.loc="C:/Users/froug/OneDrive/Documents/R/win-library/3.5")
library(readr, lib.loc="C:/Users/froug/OneDrive/Documents/R/win-library/3.5")
library(fields, lib.loc="C:/Users/froug/OneDrive/Documents/R/win-library/3.5")
library(lme4, lib.loc="C:/Users/froug/OneDrive/Documents/R/win-library/3.5")
library(ggplot2, lib.loc="C:/Users/froug/OneDrive/Documents/R/win-library/3.5")
```

## Read in the data

```{r, echo=TRUE}
kahuna <- read_csv('C:/Users/froug/Desktop/myRepo/data/2018-11-26_2017-Cape-Hatteras-BRS-kahuna-CEE.csv')
kStart <- kahuna %>% 
  filter(status == 'start')

# Read in Gm182 Data: 100 estimated positions of Gm182, augmented with focal follow data
gm182UP <- read_csv('C:/Users/froug/Desktop/myRepo/data/2018-11-27_Gm182-UserPoints-Start-CEE-Locations-Kahuna.csv') %>% 
  mutate(status = 'userPoints')

# Read in Gm182 Data: 100 estimated positions of Gm182
gm182 <- read_csv('C:/Users/froug/Desktop/myRepo/data/2018-11-27_Gm182-Start-CEE-Locations-Kahuna.csv') %>% 
  mutate(status = 'noUserPoints')

```

Now wrangle the data 

```{r}
# Minimal Wrangling of the data
gmpts <- bind_rows(gm182, gm182UP)
colnames(gmpts) <- c('trackNum', 'time', 'longitude', 'latitude', 'status')

```

Now plot

```{r}
ggplot(gmpts, aes(longitude, latitude, group = status))+
  scale_fill_gradient(low = "grey70", high = "grey30", guide = "none") +
  xlab("Longitude") +
  ylab("Latitude") +
  theme_minimal()+
  facet_grid(~ status, labeller = label_value) +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", color = "black", size = 0.2, alpha = 0.5) +
  geom_point(color = "navy", size = .5, alpha = .4)

```

Ok, now some calculations
```{r}
gmpts$d2ship <- rdist.earth.vec(cbind(kStart$longitude, kStart$latitude), 
                                cbind(gmpts$longitude, gmpts$latitude))

gmpts %>% 
  group_by(status) %>% 
  summarize(mean = mean(d2ship, na.rm = TRUE))
```

And now some model output
```{r}
gmpts.fit <- with(gmpts, lmer(d2ship ~ status + (1 | trackNum)))
summary(gmpts.fit)
```









